spring:
  application:
    name: test-native-app
  jpa:
    open-in-view: false
  security:
    user:
      name: admin
      password: secret
  cloud:
    openfeign:
      client:
        config:
          universityClient:
            url: ${UNIVERSITY_URL:}