spring:
  application:
    name: test-native-app
  jpa:
    open-in-view: false
  security:
    user:
      name: admin
      password: secret
  cloud:
    openfeign:
      client:
        config:
          universityClient:
            url: ${UNIVERSITY_URL:}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.block.ms: 5000
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"